
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=autoblogHQ
    ports:
      - '5432:5432'
